image: registry.git.fh-aachen.de/ba-vd/sfm-pipeline/rcsop-gitlab-ci:generic

stages:
  - build
  - test
  - verify

compile-gcc-12:
  stage: build
  script:
    - export CC=/usr/bin/gcc
    - export CXX=/usr/bin/g++
    - mkdir build
    - cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
    - make -j 8
  cache:
    key: "$CI_PIPELINE_ID-build"
    policy: push
    paths:
      - build/

compile-clang-14:
  stage: build
  allow_failure: true
  script:
    - export CC=/usr/bin/clang
    - export CXX=/usr/bin/clang++
    - mkdir build
    - cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
    - make -j 8

unit-tests:
  stage: test
  needs:
    - compile-gcc-12
  script:
    - cd build && ctest --output-junit ../rcsop-spec.xml
  artifacts:
    when: always
    paths:
      - rcsop-spec.xml
    reports:
      junit: rcsop-spec.xml
  cache:
    - key: "$CI_PIPELINE_ID-build"
      paths:
        - build/
      policy: pull

fetch-sample-data:
  stage: test
  needs: [ ]
  script:
    - curl -L -S -o inputs.tar.xz 'https://dobrovolskis.com/public/sfm/rcsop-input-ci.tar.xz'
    - tar -xf inputs.tar.xz
    - rm inputs.tar.xz
  cache:
    key: "$CI_PIPELINE_ID-input"
    policy: push
    paths:
      - input/

task_a-rcs_jet_0.3:
  stage: verify
  needs:
    - fetch-sample-data
    - compile-gcc-12
  script:
    - mkdir output
    - ./build/launcher/rcs-overlay-plotter --pitch-correction 2.0 --default-height 40 --color-map jet --alpha 0.3 -T "azimuth-rcs" --software-rendering -I input -O output --output-format=image
  cache:
    - key: "$CI_PIPELINE_ID-build"
      paths:
        - build/
      policy: pull
    - key: "$CI_PIPELINE_ID-input"
      paths:
        - input/
      policy: pull
  artifacts:
    paths:
      - output
    expire_in: never

task_a-rcs_red-0.6:
  stage: verify
  needs:
    - fetch-sample-data
    - compile-gcc-12
  script:
    - mkdir output
    - ./build/launcher/rcs-overlay-plotter --pitch-correction 2.0 --default-height 40 --color-map red --alpha 0.6 -T "azimuth-rcs" --software-rendering -I input -O output --output-format=image
  cache:
    - key: "$CI_PIPELINE_ID-build"
      paths:
        - build/
      policy: pull
    - key: "$CI_PIPELINE_ID-input"
      paths:
        - input/
      policy: pull
  artifacts:
    paths:
      - output
    expire_in: never

smoke-test:
  stage: test
  needs:
    - fetch-sample-data
    - compile-gcc-12
  script:
    - mkdir output
    - ./build/launcher/rcs-overlay-plotter -T "test-task" -I input -O output --default-height 40 --output-format=image
  cache:
    - key: "$CI_PIPELINE_ID-build"
      paths:
        - build/
      policy: pull
    - key: "$CI_PIPELINE_ID-input"
      paths:
        - input/
      policy: pull
  artifacts:
    paths:
      - output
    expire_in: never
