image: registry.git.fh-aachen.de/ba-vd/sfm-pipeline/rcsop-gitlab-ci:generic

cache: &global_cache
  key: $CI_PIPELINE_ID
  paths:
    - build/
    - input/
  policy: pull-push

stages:
  - build
  - test

Build launcher:
  stage: build
  script:
    - curl -L -S -o inputs.tar.xz 'https://dobrovolskis.com/public/sfm/rcsop-input-ci.tar.xz'
    - tar -xf inputs.tar.xz
    - rm inputs.tar.xz
    - mkdir build
    - cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
    - make -j 16
  cache:
    <<: *global_cache
    policy: push

Test task "Azimuth RCS":
  stage: test
  script:
    - mkdir output
    - ./build/launcher/rcs-overlay-plotter -T "azimuth-rcs" -I input -O output -M false
  cache:
    <<: *global_cache
    policy: pull
  artifacts:
    paths:
      - output
    expire_in: never

Test task "RCS slices":
  stage: test
  script:
    - mkdir output
    - ./build/launcher/rcs-overlay-plotter -T "rcs-slices" -I input -O output -M false
  cache:
    <<: *global_cache
    policy: pull
  artifacts:
    paths:
      - output
    expire_in: never

Test dummy task:
  stage: test
  script:
    - mkdir output
    - ./build/launcher/rcs-overlay-plotter -T "test-task" -I input -O output -M false
  cache:
    <<: *global_cache
    policy: pull
  artifacts:
    paths:
      - output
    expire_in: never
