#ifndef RCSOP_LAUNCHER_DEFAULT_OPTIONS_H
#define RCSOP_LAUNCHER_DEFAULT_OPTIONS_H

#include "utils/types.h"

const double DEFAULT_CAMERA_DISTANCE = 750.0;
const double CAMERA_ANGLE_CORRECTION_VERTICAL = 1.;
const height_t DEFAULT_HEIGHT = 60;

#endif //RCSOP_LAUNCHER_DEFAULT_OPTIONS_H
